---
title: The Big Guns
description: Some site description
url: 
baseurl: 
lang: en
logo: 
permalink: "/:title/"

plugins:
- jekyll-sitemap
- jekyll-paginate

exclude:
- vendor
- ".bundle"
- ".sass-cache"
- config
- Gemfile
- Gemfile.lock
- node_modules
- log
- tmp
- Rakefile
- package.json
- CHANGELOG
- LICENSE
- README
- "/docs"
sass:
  style: compressed

livereload: true

defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: blocks
  # _posts
- scope:
    path: ""
    type: posts
  values:
    layout: post

paginate:           4 # Number of posts displayed on blog page
paginate_path:      "/blog/:num/" # Blog path