---
title: The Big Guns
description: Some site description
url: 
baseurl: 
lang: en
logo: 
permalink: "/:title/"

remote_theme: carbonWinter/base

plugins:
- jekyll-sitemap
- jekyll-remote-theme

exclude:
- vendor
- ".bundle"
- ".sass-cache"
- config
- Gemfile
- Gemfile.lock
- node_modules
- log
- tmp
- Rakefile
- package.json
- CHANGELOG
- LICENSE
- README
- "/docs"
sass:
  style: compressed

livereload: true

defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: blocks
